import type { DemoStep } from './state'

const TYPED_QUERY = 'open the diff for the last commit'

const TYPING_TICKS = (() => {
  const out: { atMs: number; patch: { query: string; caretIndex: number } }[] = []
  const charMs = 105
  for (let i = 1; i <= TYPED_QUERY.length; i++) {
    out.push({
      atMs:  i * charMs,
      patch: { query: TYPED_QUERY.slice(0, i), caretIndex: i },
    })
  }
  return out
})()

const VOICE_PARTIAL_TICKS = [
  { atMs:  500, patch: { query: 'open' } },
  { atMs: 1100, patch: { query: 'open the diff' } },
  { atMs: 1900, patch: { query: 'open the diff for the' } },
  { atMs: 2700, patch: { query: 'open the diff for the last commit' } },
]

export const DEMO_SCRIPT: DemoStep[] = [
  {
    id:           'd1-rest',
    chapter:      'rest',
    chapterTitle: 'Rest',
    action:       '—',
    narration:    'Whim sits at rest.',
    explanation:  '63×9 capsule on the bottom-left edge. No labels, no chrome. Discoverability comes from one global hotkey, not from chrome.',
    sceneMutation: {
      surface:  'pill',
      pillMode: 'idle',
      cursor:   { x: 88, y: 92, visible: false },
    },
    durationMs:                       2200,
    ['data-demo-coverage-tokens']:    ['pill-idle-sliver', 'pill-edge-dock'],
  },
  {
    id:           'd2-cursor-approach',
    chapter:      'rest',
    chapterTitle: 'Rest',
    action:       'cursor →',
    narration:    'I move toward it.',
    explanation:  'Hover zone is a 73×19 wrapper around the 63×9 idle pill — five-px padding so mouseLeave never fires mid-expand.',
    sceneMutation: {
      surface:  'pill',
      pillMode: 'idle',
      cursor:   { x: 12, y: 92, visible: true },
    },
    durationMs:                       1800,
    ['data-demo-coverage-tokens']:    ['pill-hover-zone', 'ghost-cursor'],
  },
  {
    id:           'd3-hover-preview',
    chapter:      'summon',
    chapterTitle: 'Summon',
    action:       'hover',
    narration:    'I hover.',
    explanation:  'Pill morphs to 126×36 with 18 px radius. Reveals input + mic + conv-count badge. Same DOM node — only width/height/radius move.',
    sceneMutation: {
      surface:  'pill',
      pillMode: 'hover',
      cursor:   { x: 12, y: 92, visible: true },
    },
    durationMs:                       2200,
    ['data-demo-coverage-tokens']:    ['pill-hover-row', 'pill-conv-badge', 'pill-mic-glyph'],
  },
  {
    id:           'd4-summon-key',
    chapter:      'summon',
    chapterTitle: 'Summon',
    action:       '⌥Space',
    narration:    'I press ⌥Space.',
    explanation:  'KeyHUD flashes the chord. The pill is about to take focus — substrate doesn\'t switch yet, the user owns the transition.',
    sceneMutation: {
      surface:    'pill',
      pillMode:   'hover',
      cursor:     { x: 12, y: 92, visible: false },
      pressedKey: '⌥Space',
    },
    durationMs:                       1200,
    ['data-demo-coverage-tokens']:    ['pill-summon-key', 'key-hud-chord'],
  },
  {
    id:           'd5-pill-to-palette',
    chapter:      'compose',
    chapterTitle: 'Compose',
    action:       '→ palette',
    narration:    'The palette opens in place.',
    explanation:  '820×520 palette. Same component as the pill, scale prop flipped. Width interpolates over 250 ms — no pop-in window.',
    sceneMutation: {
      surface:  'palette',
      pillMode: 'type',
      cursor:   { x: 50, y: 50, visible: false },
      query:    '',
    },
    callout: {
      title: 'Same DOM node, scale interpolated',
      body:  'No remount. width/height/transform animate; children cross-fade.',
    },
    durationMs:                       2600,
    ['data-demo-coverage-tokens']:    ['palette-open', 'palette-shell-820', 'scale-interpolation'],
  },
  {
    id:           'd6-type-prompt',
    chapter:      'compose',
    chapterTitle: 'Compose',
    action:       'type…',
    narration:    'I type "open the diff for the last commit".',
    explanation:  'Composer is recording off, drafting on. Caret advances character-by-character; placeholder fades. Mode communicated by icon.',
    sceneMutation: {
      surface:    'palette',
      pillMode:   'type',
      cursor:     { x: 50, y: 32, visible: false },
      query:      '',
      caretIndex: 0,
    },
    durationMs:                       3800,
    ticks:                            TYPING_TICKS,
    ['data-demo-coverage-tokens']:    ['palette-input', 'palette-typing-caret', 'palette-placeholder'],
  },
  {
    id:           'd7-grouped-results',
    chapter:      'compose',
    chapterTitle: 'Compose',
    action:       'results',
    narration:    'Results group themselves.',
    explanation:  'Actions · Recent · Projects · Tracker · Plugins. Top match wins focus; ↑↓ moves; ↵ selects. No tabs, no filters.',
    sceneMutation: {
      surface: 'palette',
      cursor:  { x: 50, y: 48, visible: false },
      query:   TYPED_QUERY,
    },
    durationMs:                       2400,
    ['data-demo-coverage-tokens']:    [
      'palette-results',
      'palette-section-actions',
      'palette-section-recent',
      'palette-section-projects',
      'palette-section-tracker',
      'palette-section-plugins',
    ],
  },
  {
    id:           'd8-arrow-down',
    chapter:      'compose',
    chapterTitle: 'Compose',
    action:       '↓',
    narration:    'I press ↓ to widen the search.',
    explanation:  'Visual-only key — the demo doesn\'t intercept arrows; it shows them. Recognition over recall: every shortcut sits beside its action.',
    sceneMutation: {
      surface:    'palette',
      cursor:     { x: 50, y: 48, visible: false },
      pressedKey: '↓',
    },
    durationMs:                       1400,
    ['data-demo-coverage-tokens']:    ['palette-arrow-key'],
  },
  {
    id:           'd9-voice-decide',
    chapter:      'voice',
    chapterTitle: 'Voice',
    action:       'voice cue',
    narration:    "I'd rather speak it.",
    explanation:  'Narration cue. The composer is still focused — voice doesn\'t open a new surface; it sub-states the same composer.',
    sceneMutation: {
      surface: 'palette',
      cursor:  { x: 50, y: 32, visible: false },
    },
    durationMs:                       1400,
    ['data-demo-coverage-tokens']:    ['palette-voice-cue'],
  },
  {
    id:           'd10-vhold-down',
    chapter:      'voice',
    chapterTitle: 'Voice',
    action:       'V',
    narration:    'I hold V.',
    explanation:  'After 200 ms of V-hold, composer enters recording-vhold. A 9-bin overlay paints over the input row. Any mode change cancels.',
    sceneMutation: {
      surface:    'palette',
      cursor:     { x: 50, y: 32, visible: false },
      pressedKey: 'V',
      query:      '',
    },
    durationMs:                       1800,
    ['data-demo-coverage-tokens']:    ['palette-vhold-down', 'voice-overlay-9bin'],
  },
  {
    id:           'd11-vhold-record',
    chapter:      'voice',
    chapterTitle: 'Voice',
    action:       'V (held)',
    narration:    'I dictate.',
    explanation:  'Live STT partial transcript renders below the bins. The pill mode flag flips to voice so the L0 box doesn\'t spuriously redraw.',
    sceneMutation: {
      surface:   'palette',
      pillMode:  'voice',
      recording: true,
      cursor:    { x: 50, y: 32, visible: false },
      query:     '',
    },
    durationMs:                       3200,
    ticks:                            VOICE_PARTIAL_TICKS,
    ['data-demo-coverage-tokens']:    ['voice-recording', 'voice-partial-transcript'],
  },
  {
    id:           'd12-vhold-release',
    chapter:      'voice',
    chapterTitle: 'Voice',
    action:       'release',
    narration:    'I release V.',
    explanation:  'Transcript pastes into the composer with caret at the end. Whim never auto-submits a dictation — the user always edits before sending.',
    sceneMutation: {
      surface:    'palette',
      pillMode:   'type',
      recording:  false,
      cursor:     { x: 50, y: 32, visible: false },
      query:      TYPED_QUERY,
      caretIndex: TYPED_QUERY.length,
    },
    durationMs:                       2000,
    ['data-demo-coverage-tokens']:    ['voice-release', 'voice-paste-composer'],
  },
  {
    id:           'd13-edit-prompt',
    chapter:      'compose',
    chapterTitle: 'Compose',
    action:       'tweak',
    narration:    'I tweak the prompt.',
    explanation:  'Caret moves; chips below the input update token estimate live. Chips are status, not nav — clicking opens a popover, never a window.',
    sceneMutation: {
      surface: 'palette',
      cursor:  { x: 50, y: 32, visible: false },
      query:   TYPED_QUERY,
    },
    durationMs:                       2400,
    ['data-demo-coverage-tokens']:    ['composer-edit', 'composer-chips'],
  },
  {
    id:           'd14-submit',
    chapter:      'submit',
    chapterTitle: 'Submit',
    action:       '↵',
    narration:    'I press ↵.',
    explanation:  'Optimistic submit. The user\'s turn echoes into a chat rail before the workspace is allocated. Perceived latency is owned, not spun.',
    sceneMutation: {
      surface:    'palette',
      cursor:     { x: 50, y: 32, visible: false },
      pressedKey: '↵',
    },
    durationMs:                       1600,
    ['data-demo-coverage-tokens']:    ['composer-submit', 'composer-optimistic-echo'],
  },
  {
    id:           'd15-palette-to-cv',
    chapter:      'canvas',
    chapterTitle: 'Canvas',
    action:       '→ canvas',
    narration:    'The substrate flips to the mission canvas.',
    explanation:  'Palette children fade out, canvas children fade in — same root div, scale interpolated. The transcript anchors to the eye\'s last fix.',
    sceneMutation: {
      surface: 'canvas',
      cursor:  { x: 50, y: 50, visible: false },
    },
    callout: {
      title: 'One root, four surfaces',
      body:  'Children cross-fade by opacity; layout interpolates by width/height.',
    },
    durationMs:                       2200,
    ['data-demo-coverage-tokens']:    ['canvas-mount', 'canvas-cross-fade'],
  },
  {
    id:           'd16-runlog',
    chapter:      'canvas',
    chapterTitle: 'Canvas',
    action:       'run log',
    narration:    'A run log appears, one row per phase.',
    explanation:  'Phase rows transition ○ → ✓ with a live duration counter. Tool chatter stays hidden — one line per phase, not per tool call.',
    sceneMutation: {
      surface: 'canvas',
      cursor:  { x: 24, y: 56, visible: true },
    },
    durationMs:                       3200,
    ['data-demo-coverage-tokens']:    ['canvas-runlog', 'runlog-phase-row'],
  },
  {
    id:           'd17-terminal-open',
    chapter:      'canvas',
    chapterTitle: 'Canvas',
    action:       '⌘J',
    narration:    'I press ⌘J for the terminal.',
    explanation:  'A 240-px drawer docks at the bottom; the canvas reflows up. Docks push, overlays float — that\'s the rule.',
    sceneMutation: {
      surface:    'canvas',
      cursor:     { x: 24, y: 56, visible: false },
      pressedKey: '⌘J',
    },
    durationMs:                       2200,
    ['data-demo-coverage-tokens']:    ['terminal-drawer-open'],
  },
  {
    id:           'd18-terminal-close',
    chapter:      'canvas',
    chapterTitle: 'Canvas',
    action:       '⌘J',
    narration:    'I press ⌘J again.',
    explanation:  'Drawer collapses; canvas reflows down. Toggle is symmetric — closing is hide, not reset.',
    sceneMutation: {
      surface:    'canvas',
      cursor:     { x: 24, y: 56, visible: false },
      pressedKey: '⌘J',
    },
    durationMs:                       1600,
    ['data-demo-coverage-tokens']:    ['terminal-drawer-close'],
  },
  {
    id:           'd19-rail-files',
    chapter:      'canvas',
    chapterTitle: 'Canvas',
    action:       '⌘B',
    narration:    'I open the right rail with ⌘B.',
    explanation:  '300-px rail mounts in files mode by default — the FilesPanel from slice-2. Rail mode survives close + reopen.',
    sceneMutation: {
      surface:    'canvas',
      cursor:     { x: 88, y: 24, visible: true },
      pressedKey: '⌘B',
    },
    durationMs:                       2400,
    ['data-demo-coverage-tokens']:    ['right-rail-files'],
  },
  {
    id:           'd20-mission-done',
    chapter:      'canvas',
    chapterTitle: 'Canvas',
    action:       '✓ done',
    narration:    'The mission completes.',
    explanation:  'A Changed-Files card surfaces inline (CHANGED FILES (N) • +X / −Y) with a per-file plain-English summary. First-class block, not banner.',
    sceneMutation: {
      surface: 'canvas',
      cursor:  { x: 50, y: 50, visible: false },
    },
    durationMs:                       2600,
    ['data-demo-coverage-tokens']:    ['mission-done', 'changed-files-card'],
  },
  {
    id:           'd21-view-diff',
    chapter:      'diff',
    chapterTitle: 'Diff',
    action:       '⌘D',
    narration:    'I press ⌘D to view the diff.',
    explanation:  'The right rail flips to turn-diff mode and the diff viewer takes the hero column. Modal: the next 11 keys live only here.',
    sceneMutation: {
      surface:    'canvas',
      cursor:     { x: 50, y: 64, visible: true },
      pressedKey: '⌘D',
    },
    durationMs:                       2000,
    ['data-demo-coverage-tokens']:    ['diff-open-key', 'right-rail-turn-diff'],
  },
  {
    id:           'd22-diff-hero',
    chapter:      'diff',
    chapterTitle: 'Diff',
    action:       'hero',
    narration:    'The diff viewer is Whim\'s hero.',
    explanation:  'Side-by-side hunks, current hunk haloed. The grammar is modal — y/n/j/k/a/Y/⇧A/⌘[/⌘]/c/⌘Z/r — inert outside the viewer.',
    sceneMutation: {
      surface: 'diff',
      cursor:  { x: 50, y: 50, visible: true },
    },
    callout: {
      title: 'Modal grammar — 11 keys',
      body:  'y · n · j · k · a · Y · ⇧A · ⌘[ · ⌘] · c · r — scoped to the diff.',
    },
    durationMs:                       3200,
    ['data-demo-coverage-tokens']:    ['diff-hero', 'diff-hunk-active'],
  },
  {
    id:           'd23-accept-hunk',
    chapter:      'diff',
    chapterTitle: 'Diff',
    action:       'y',
    narration:    'I press y to accept this hunk.',
    explanation:  'The hunk applies; cursor advances to the next. Single-key actions because review fatigue is the failure mode, not slow apply.',
    sceneMutation: {
      surface:    'diff',
      cursor:     { x: 50, y: 50, visible: false },
      pressedKey: 'y',
    },
    durationMs:                       1800,
    ['data-demo-coverage-tokens']:    ['diff-accept-hunk'],
  },
  {
    id:           'd24-next-hunk',
    chapter:      'diff',
    chapterTitle: 'Diff',
    action:       'j',
    narration:    'j moves to the next hunk.',
    explanation:  'j/k navigate hunks; ⌘[/⌘] navigate files. The same modal vocabulary as Vim, scoped to the diff viewer only.',
    sceneMutation: {
      surface:    'diff',
      cursor:     { x: 50, y: 50, visible: false },
      pressedKey: 'j',
    },
    durationMs:                       1600,
    ['data-demo-coverage-tokens']:    ['diff-next-hunk'],
  },
  {
    id:           'd25-reject-hunk',
    chapter:      'diff',
    chapterTitle: 'Diff',
    action:       'n',
    narration:    'I press n to reject this one.',
    explanation:  'The hunk reverts; the chat rail records the rejection so the model can re-read on retry. r re-applies after a fix.',
    sceneMutation: {
      surface:    'diff',
      cursor:     { x: 50, y: 50, visible: false },
      pressedKey: 'n',
    },
    durationMs:                       1800,
    ['data-demo-coverage-tokens']:    ['diff-reject-hunk'],
  },
  {
    id:           'd26-accept-file',
    chapter:      'diff',
    chapterTitle: 'Diff',
    action:       'Y',
    narration:    'Y accepts the whole file.',
    explanation:  'Cap accent for primary action — the keycap glows. Bulk operations exist but require a separate key, never a misclick away.',
    sceneMutation: {
      surface:    'diff',
      cursor:     { x: 50, y: 50, visible: false },
      pressedKey: 'Y',
    },
    durationMs:                       1600,
    ['data-demo-coverage-tokens']:    ['diff-accept-file'],
  },
  {
    id:           'd27-commit',
    chapter:      'diff',
    chapterTitle: 'Diff',
    action:       'c',
    narration:    'c commits the accepted set.',
    explanation:  'Commit message pre-fills from the mission\'s plain-English summaries. Commits are keystrokes, not modal forms.',
    sceneMutation: {
      surface:    'diff',
      cursor:     { x: 50, y: 50, visible: false },
      pressedKey: 'c',
    },
    durationMs:                       2200,
    ['data-demo-coverage-tokens']:    ['diff-commit'],
  },
  {
    id:           'd28-back-to-canvas',
    chapter:      'wrap',
    chapterTitle: 'Wrap',
    action:       'Esc',
    narration:    'Esc steps back one rung.',
    explanation:  'Esc never skips a rung. Diff (L4) → canvas (L3). The Tour itself owns its rung; one Esc, one step back.',
    sceneMutation: {
      surface:    'canvas',
      cursor:     { x: 50, y: 50, visible: false },
      pressedKey: 'Esc',
    },
    durationMs:                       1800,
    ['data-demo-coverage-tokens']:    ['esc-back-canvas'],
  },
  {
    id:           'd29-canvas-to-pill',
    chapter:      'wrap',
    chapterTitle: 'Wrap',
    action:       'Esc',
    narration:    'Esc again — back to rest.',
    explanation:  'Canvas (L3) → query (L1) → pill (L0). The substrate collapses by reversing the same scale interpolation it expanded with.',
    sceneMutation: {
      surface:    'pill',
      pillMode:   'idle',
      cursor:     { x: 12, y: 92, visible: true },
      pressedKey: 'Esc',
      query:      '',
    },
    durationMs:                       2400,
    ['data-demo-coverage-tokens']:    ['esc-back-pill'],
  },
  {
    id:           'd30-final-rest',
    chapter:      'rest',
    chapterTitle: 'Rest',
    action:       '—',
    narration:    'Whim returns to the edge.',
    explanation:  '63×9 again. Same node, same anchor, same dock. The session left no chrome behind — the workspace is a side effect, not a destination.',
    sceneMutation: {
      surface:  'pill',
      pillMode: 'idle',
      cursor:   { x: 88, y: 92, visible: false },
      query:    '',
    },
    durationMs:                       2400,
    ['data-demo-coverage-tokens']:    ['pill-final-rest'],
  },
]
