// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelMission(arg1) {
  return window['go']['main']['App']['CancelMission'](arg1);
}

export function Cleanup() {
  return window['go']['main']['App']['Cleanup']();
}

export function DisableInteraction() {
  return window['go']['main']['App']['DisableInteraction']();
}

export function EnableInteraction(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EnableInteraction'](arg1, arg2, arg3, arg4);
}

export function GetChannelStatus() {
  return window['go']['main']['App']['GetChannelStatus']();
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetKoResults() {
  return window['go']['main']['App']['GetKoResults']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetMission(arg1) {
  return window['go']['main']['App']['GetMission'](arg1);
}

export function GetMissionDAG(arg1) {
  return window['go']['main']['App']['GetMissionDAG'](arg1);
}

export function GetMissionDetail(arg1) {
  return window['go']['main']['App']['GetMissionDetail'](arg1);
}

export function GetPersonaDetail(arg1) {
  return window['go']['main']['App']['GetPersonaDetail'](arg1);
}

export function GetPluginCapabilities() {
  return window['go']['main']['App']['GetPluginCapabilities']();
}

export function GetPluginHealth() {
  return window['go']['main']['App']['GetPluginHealth']();
}

export function GetPluginUIBundle(arg1) {
  return window['go']['main']['App']['GetPluginUIBundle'](arg1);
}

export function GetRyuReport() {
  return window['go']['main']['App']['GetRyuReport']();
}

export function ListMissions() {
  return window['go']['main']['App']['ListMissions']();
}

export function ListPersonas() {
  return window['go']['main']['App']['ListPersonas']();
}

export function ListPlugins() {
  return window['go']['main']['App']['ListPlugins']();
}

export function ListScanners() {
  return window['go']['main']['App']['ListScanners']();
}

export function LiveMissionURL(arg1) {
  return window['go']['main']['App']['LiveMissionURL'](arg1);
}

export function NenHealth() {
  return window['go']['main']['App']['NenHealth']();
}

export function NenScan() {
  return window['go']['main']['App']['NenScan']();
}

export function OrchestratorHealth() {
  return window['go']['main']['App']['OrchestratorHealth']();
}

export function PluginAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginAction'](arg1, arg2, arg3);
}

export function QueryPluginItems(arg1) {
  return window['go']['main']['App']['QueryPluginItems'](arg1);
}

export function QueryPluginStatus(arg1) {
  return window['go']['main']['App']['QueryPluginStatus'](arg1);
}

export function ReloadPersonas() {
  return window['go']['main']['App']['ReloadPersonas']();
}

export function RunMission(arg1, arg2) {
  return window['go']['main']['App']['RunMission'](arg1, arg2);
}

export function SchedulerHealth() {
  return window['go']['main']['App']['SchedulerHealth']();
}

export function StartChat(arg1, arg2) {
  return window['go']['main']['App']['StartChat'](arg1, arg2);
}

export function StreamChat(arg1) {
  return window['go']['main']['App']['StreamChat'](arg1);
}

export function TrackerItems() {
  return window['go']['main']['App']['TrackerItems']();
}

export function TrackerStats() {
  return window['go']['main']['App']['TrackerStats']();
}

export function TrackerUpdate(arg1) {
  return window['go']['main']['App']['TrackerUpdate'](arg1);
}
