// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelMission(arg1:string):Promise<string>;

export function Cleanup():Promise<string>;

export function DisableInteraction():Promise<void>;

export function EnableInteraction(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function GetChannelStatus():Promise<string>;

export function GetConversation(arg1:string):Promise<string>;

export function GetKoResults():Promise<string>;

export function GetMetrics():Promise<string>;

export function GetMission(arg1:string):Promise<string>;

export function GetMissionDAG(arg1:string):Promise<string>;

export function GetMissionDetail(arg1:string):Promise<string>;

export function GetPersonaDetail(arg1:string):Promise<string>;

export function GetPluginCapabilities():Promise<string>;

export function GetPluginHealth():Promise<string>;

export function GetPluginUIBundle(arg1:string):Promise<string>;

export function GetRyuReport():Promise<string>;

export function ListMissions():Promise<string>;

export function ListPersonas():Promise<string>;

export function ListPlugins():Promise<Array<main.PluginManifest>>;

export function ListScanners():Promise<string>;

export function LiveMissionURL(arg1:string):Promise<string>;

export function NenHealth():Promise<string>;

export function NenScan():Promise<string>;

export function OrchestratorHealth():Promise<string>;

export function PluginAction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function QueryPluginItems(arg1:string):Promise<string>;

export function QueryPluginStatus(arg1:string):Promise<string>;

export function ReloadPersonas():Promise<string>;

export function RunMission(arg1:string,arg2:string):Promise<string>;

export function SchedulerHealth():Promise<string>;

export function StartChat(arg1:string,arg2:string):Promise<string>;

export function StreamChat(arg1:string):Promise<void>;

export function TrackerItems():Promise<string>;

export function TrackerStats():Promise<string>;

export function TrackerUpdate(arg1:string):Promise<string>;
