package main

import (
	"bufio"
	"context"
	"database/sql"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"
)

// sweepOptions configures how runCloseSweep behaves.
type sweepOptions struct {
	MissionDir       string
	DryRun           bool
	ConservativeMode bool // if true, only handles "all findings superseded" branch
}

// sweepReport summarises the results of a sweep run.
type sweepReport struct {
	Total             int      `json:"total"`
	AlreadyDone       int      `json:"already_done"`
	SweptToDone       int      `json:"swept_to_done"`
	ClosedViaInternal int      `json:"closed_via_internal"`
	Skipped           int      `json:"skipped"`
	Invalid           int      `json:"invalid"`
	Errors            []string `json:"errors,omitempty"`
}

// remediationMissionMeta holds the frontmatter fields the sweep needs.
type remediationMissionMeta struct {
	TrackerIssue string
	FindingIDs   []string
	GeneratedAt  time.Time
}

// parseRemediationMissionMeta reads and parses the YAML frontmatter from a
// remediation mission file. Returns an error if the block is missing or
// required fields are absent. Does not require a YAML library — the
// frontmatter is generated by shu and has a fixed shape.
func parseRemediationMissionMeta(path string) (remediationMissionMeta, error) {
	f, err := os.Open(path)
	if err != nil {
		return remediationMissionMeta{}, fmt.Errorf("open %s: %w", path, err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)

	// Expect the file to start with "---".
	if !scanner.Scan() || strings.TrimSpace(scanner.Text()) != "---" {
		return remediationMissionMeta{}, fmt.Errorf("%s: missing YAML frontmatter opening ---", path)
	}

	var meta remediationMissionMeta
	inFindingIDs := false

	for scanner.Scan() {
		line := scanner.Text()
		if strings.TrimSpace(line) == "---" {
			break // end of frontmatter
		}

		// Multi-line list under finding_ids: / finding_ids :
		if inFindingIDs {
			trimmed := strings.TrimSpace(line)
			if strings.HasPrefix(trimmed, "- ") {
				meta.FindingIDs = append(meta.FindingIDs, strings.TrimSpace(strings.TrimPrefix(trimmed, "- ")))
				continue
			}
			// Any non-list line ends the finding_ids block.
			inFindingIDs = false
		}

		// Parse key: value pairs.
		idx := strings.IndexByte(line, ':')
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(line[:idx])
		val := strings.TrimSpace(line[idx+1:])
		// Strip surrounding quotes.
		val = strings.Trim(val, `"'`)

		switch key {
		case "tracker_issue":
			meta.TrackerIssue = val
		case "finding_ids":
			// Value may be empty on this line; list items follow on subsequent lines.
			if val != "" && val != "[]" {
				meta.FindingIDs = append(meta.FindingIDs, val)
			}
			inFindingIDs = true
		case "generated_at":
			if t, err := time.Parse(time.RFC3339, val); err == nil {
				meta.GeneratedAt = t
			}
		}
	}
	if err := scanner.Err(); err != nil {
		return remediationMissionMeta{}, fmt.Errorf("reading %s: %w", path, err)
	}

	if meta.TrackerIssue == "" {
		return remediationMissionMeta{}, fmt.Errorf("%s: frontmatter missing tracker_issue", path)
	}
	if len(meta.FindingIDs) == 0 {
		return remediationMissionMeta{}, fmt.Errorf("%s: frontmatter missing finding_ids", path)
	}
	return meta, nil
}

// allFindingsSuperseded queries findings.db and returns true when every finding
// ID in the list has a non-empty superseded_by. Missing IDs (never inserted)
// are treated as superseded — they cannot be active.
func allFindingsSuperseded(ids []string) (bool, error) {
	path := findingsDBPath()
	if _, err := os.Stat(path); os.IsNotExist(err) {
		// No findings DB at all — treat everything as superseded (nothing to close).
		return true, nil
	}
	db, err := sql.Open("sqlite", "file:"+path+"?mode=ro")
	if err != nil {
		return false, fmt.Errorf("open findings.db: %w", err)
	}
	defer db.Close()

	placeholders := make([]string, len(ids))
	args := make([]any, len(ids))
	for i, id := range ids {
		placeholders[i] = "?"
		args[i] = id
	}

	rows, err := db.Query(
		fmt.Sprintf("SELECT id, superseded_by FROM findings WHERE id IN (%s)", strings.Join(placeholders, ",")),
		args...,
	)
	if err != nil {
		return false, fmt.Errorf("querying findings: %w", err)
	}
	defer rows.Close()

	activeCount := 0
	for rows.Next() {
		var id, supersededBy string
		if err := rows.Scan(&id, &supersededBy); err != nil {
			return false, fmt.Errorf("scanning finding: %w", err)
		}
		if supersededBy == "" {
			activeCount++
		}
	}
	if err := rows.Err(); err != nil {
		return false, fmt.Errorf("iterating findings: %w", err)
	}
	return activeCount == 0, nil
}

// trackerIssueStatus calls `tracker show <id> --json` and returns the status
// field, or "" on error.
func trackerIssueStatus(ctx context.Context, issueID string) (string, error) {
	out, err := exec.CommandContext(ctx, "tracker", "show", issueID, "--json").Output()
	if err != nil {
		return "", fmt.Errorf("tracker show %s: %w", issueID, err)
	}
	// Parse just the status field with a simple search to avoid import bloat.
	// Output is a JSON object; look for "status":"<value>".
	raw := string(out)
	const key = `"status":`
	idx := strings.Index(raw, key)
	if idx < 0 {
		return "", fmt.Errorf("tracker show %s: no status field in output", issueID)
	}
	rest := strings.TrimSpace(raw[idx+len(key):])
	rest = strings.TrimPrefix(rest, `"`)
	end := strings.IndexByte(rest, '"')
	if end < 0 {
		return "", fmt.Errorf("tracker show %s: unparseable status", issueID)
	}
	return rest[:end], nil
}

// markTrackerDone calls `tracker update <id> --status done` and adds a comment.
func markTrackerDone(issueID, comment string, dryRun bool) error {
	if dryRun {
		return nil
	}
	if out, err := exec.Command("tracker", "update", issueID, "--status", "done").CombinedOutput(); err != nil {
		return fmt.Errorf("tracker update %s --status done: %s: %w", issueID, strings.TrimSpace(string(out)), err)
	}
	// Non-fatal comment.
	_ = exec.Command("tracker", "comment", issueID, comment).Run()
	return nil
}

// runCloseSweep scans the remediation mission directory and reconciles tracker
// issues whose findings are already resolved. In conservative mode (always
// enabled for now), it only handles the "all findings superseded" branch.
func runCloseSweep(ctx context.Context, opts sweepOptions) (sweepReport, error) {
	var report sweepReport

	entries, err := os.ReadDir(opts.MissionDir)
	if err != nil {
		if os.IsNotExist(err) {
			return report, nil // empty dir → all zeros, not an error
		}
		return report, fmt.Errorf("reading remediation dir: %w", err)
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}
		report.Total++
		path := opts.MissionDir + "/" + entry.Name()

		meta, err := parseRemediationMissionMeta(path)
		if err != nil {
			report.Invalid++
			report.Errors = append(report.Errors, fmt.Sprintf("%s: %v", entry.Name(), err))
			continue
		}

		// Query current tracker status.
		status, err := trackerIssueStatus(ctx, meta.TrackerIssue)
		if err != nil {
			report.Skipped++
			report.Errors = append(report.Errors, fmt.Sprintf("%s: querying %s: %v", entry.Name(), meta.TrackerIssue, err))
			continue
		}

		switch status {
		case "done":
			report.AlreadyDone++
			continue
		case "cancelled", "closed":
			// Rejected or manually closed — don't touch findings.
			report.Skipped++
			continue
		case "open", "in-progress":
			superseded, err := allFindingsSuperseded(meta.FindingIDs)
			if err != nil {
				report.Skipped++
				report.Errors = append(report.Errors, fmt.Sprintf("%s: checking findings: %v", entry.Name(), err))
				continue
			}
			if !superseded {
				// Conservative mode: skip — mission may still be running.
				report.Skipped++
				continue
			}
			// All findings already superseded — safe to close tracker issue.
			if err := markTrackerDone(meta.TrackerIssue,
				"swept: findings already superseded out-of-band",
				opts.DryRun,
			); err != nil {
				report.Errors = append(report.Errors, fmt.Sprintf("%s: marking done: %v", entry.Name(), err))
				report.Skipped++
				continue
			}
			report.SweptToDone++
		default:
			report.Skipped++
		}
	}
	return report, nil
}
